
[Relays]
[Relays.relay_nostr_wirednet_jp]
name = ""
address = "wss://relay.nostr.wirednet.jp"
description = "World wide relay"
description_ja = "ワールドワイドリレー"
author_name = ["imksoo"]
author_url = ["https://github.com/imksoo"]

[Relays.relay-jp_nostr_wirednet_jp]
name = ""
address = "wss://relay-jp.nostr.wirednet.jp"
description = "Japanese oriented relay"
description_ja = "日本向けリレー"
author_name = ["imksoo"]
author_url = ["https://github.com/imksoo"]

[Relays.ipv6_nostr_wirednet_jp]
name = ""
address = "wss://ipv6.nostr.wirednet.jp"
description = "ipv6 relay"
description_ja = "ipv6リレー"
author_name = ["imksoo"]
author_url = ["https://github.com/imksoo"]

[Relays.nostr_holybea_com]
name = ""
address = "wss://nostr.holybea.com"
description = ""
description_ja = ""
author_name = ["ほりべあ"]
author_url = ["https://holybea.com"]

[Relays.nostr_fediverse_jp]
name = ""
address = "wss://nostr.fediverse.jp"
description = ""
description_ja = ""
author_name = ["αυγοτάραχο σολωμου"]
author_url = [
    "https://nostx.shino3.net/npub1xmqfm9s0yxyadzjh0cp7gsf7fxy0xfgaq23cp9p7fnee6cehrlxq6c6tkw",
]

[Relays.yabu_me]
name = ""
address = "wss://yabu.me"
description = "Aggregator relay for (mainly) Japanese users."
description_ja = "(主に) 日本ユーザー向けのアグリゲーターリレー"
author_name = ["αυγοτάραχο σολωμου"]
author_url = [
    "https://yabu.me/npub1kurad0nlm8xfuxhws05pcwv5z4k0ea6da4dsjygexr77a666pssqsftsm7",
]

[Relays.nostr-relay_nokotaro_com]
name = ""
address = "wss://nostr-relay.nokotaro.com"
description = "World wide relay"
description_ja = "ワールドワイドリレー"
author_name = ["Nokotaro Takeda"]
author_url = ["https://github.com/nokotaro"]

[Relays.nrelay_c-stellar_net]
name = ""
address = "wss://nrelay.c-stellar.net"
description = "Relay that only allows followers of the operator to write"
description_ja = "運営者のフォロワーのみ書き込み可能なリレー"
author_name = ["jiftechnify"]
author_url = ["https://github.com/jiftechnify"]

[Relays.nrelay-jp_c-stellar_net]
name = ""
address = "wss://nrelay-jp.c-stellar.net"
description = "Japanese oriented relay"
description_ja = "日本向けリレー"
author_name = ["jiftechnify"]
author_url = ["https://github.com/jiftechnify"]

[Relays.relay_yozora_world]
name = ""
address = "wss://relay.yozora.world"
description = "Paid relay via Starlink's satellite network"
description_ja = "Starlinkの衛星回線のみで運用されている有料リレー"
author_name = ["godzhigella"]
author_url = ["https://github.com/higedamc"]

[Relays.r_kojira_io]
name = ""
address = "wss://r.kojira.io"
description = "Japanese oriented relay"
description_ja = "日本向けリレー"
author_name = ["kojira"]
author_url = ["https://github.com/kojira"]

[Relays.nostr_compile_error_net]
name = ""
address = "wss://nostr.compile-error.net"
description = "Japanese oriented relay written in Go"
description_ja = "Go で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]

[Relays.cagliostr_compile_error_net]
name = ""
address = "wss://cagliostr.compile-error.net"
description = "Japanese oriented relay written in C++"
description_ja = "C++ で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]

[Relays.lua-nostr-relay_compile_error_net]
name = ""
address = "wss://lua-nostr-relay.compile-error.net"
description = "Japanese oriented relay written in Lua"
description_ja = "Lua で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]

[Relays.lisp-nostr-relay_compile_error_net]
name = ""
address = "wss://lisp-nostr-relay.compile-error.net"
description = "Japanese oriented relay written in Common Lisp"
description_ja = "Common Lisp で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]

[Relays.ruby-nostr-relay_compile_error_net]
name = ""
address = "wss://ruby-nostr-relay.compile-error.net"
description = "Japanese oriented relay written in Ruby"
description_ja = "Ruby で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]

[Relays.nim-nostr-relay_compile_error_net]
name = ""
address = "wss://nim-nostr-relay.compile-error.net"
description = "Japanese oriented relay written in Nim"
description_ja = "Nim で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]

[Relays.crystal-nostr-relay_compile_error_net]
name = ""
address = "wss://crystal-nostr-relay.compile-error.net"
description = "Japanese oriented relay written in Crystal"
description_ja = "Crystal で書かれた日本向けリレー"
author_name = ["mattn"]
author_url = ["https://github.com/mattn"]
